### ISSUE TITLE
DNS check can hang

### ISSUE THREAD

**Issue by konklone** [benbalter/site-inspector-ruby#18]
This hangs for me entirely, I can't even Ctrl-C it:

```ruby
Dnsruby::Resolver.new.query("konklone.com", "ANY")
```

I can't figure out why this would be -- it may not be a `site-inspector` problem, but do you have any idea?

This brings up another thing, though - just running `site-inspector domain.com` runs through the *whole* gamut of checks. If I'm not interested in DNS-based checks, I'd love to be able to just do `site-inspector --lite domain.com` or something like that, to speed up batch processing.

**Comment by konklone** [comment]
FWIW, it returns extremely quickly when run from my server -- the issue appears to be constrained to my local machine.

**Comment by konklone** [comment]
And, here's my error log of the DNS check. It goes into a recursive error tree and keeps spitting out details about an invalid blank nameserver argument. Ugh.

https://gist.github.com/konklone/e2393201cc6310486d7c

This seems like a Dnsruby bug, based on invalid or unexpected input from my home ISP (Comcast). I can confirm also that by tethering off of my T-Mobile 4G, the problem does not appear.

**Comment by benbalter** [comment]
Yeah, I'm thinking the solution may be to hard-code Google DNS to avoid errors like this (I've experienced dns quirks as well)
